packages:
    - "apps/*"
    - "packages/*"

onlyBuiltDependencies:
    - "@firebase/util"
    - "@nestjs/core"
    - "@vercel/speed-insights"
    - argon2
    - esbuild
    - mongodb-memory-server
    - protobufjs
    - unrs-resolver
