/**
 * Compatibility aliases for legacy web imports. Generated by scripts/sync-api-types.mjs
 * The file provides aliases so web code can keep importing old names while we migrate
 * them to the canonical `./api` exports. TODO: remove this file after updating imports.
 */

// TODO: CheckoutResponse not found in generated api.ts - please map or remove
export type CheckoutResponse = any;
// TODO: CreateCheckoutRequest not found in generated api.ts - please map or remove
export type CreateCheckoutRequest = any;
// TODO: PaymentListParams not found in generated api.ts - please map or remove
export type PaymentListParams = any;
// TODO: PaymentStatusResponse not found in generated api.ts - please map or remove
export type PaymentStatusResponse = any;
// TODO: PollStatusResponse not found in generated api.ts - please map or remove
export type PollStatusResponse = any;
// TODO: UserPaymentListResponse not found in generated api.ts - please map or remove
export type UserPaymentListResponse = any;
// TODO: ApiPurchaseItem not found in generated api.ts - please map or remove
export type ApiPurchaseItem = any;
// TODO: Achievement not found in generated api.ts - please map or remove
export type Achievement = any;
// TODO: AnalyzeConsumptionRequest not found in generated api.ts - please map or remove
export type AnalyzeConsumptionRequest = any;
// TODO: AuthResponse not found in generated api.ts - please map or remove
export type AuthResponse = any;
// TODO: BalanceProjection not found in generated api.ts - please map or remove
export type BalanceProjection = any;
// TODO: BankAccount not found in generated api.ts - please map or remove
export type BankAccount = any;
// TODO: BankTransaction not found in generated api.ts - please map or remove
export type BankTransaction = any;
// TODO: BudgetProgress not found in generated api.ts - please map or remove
export type BudgetProgress = any;
// TODO: BulkDeletePurchaseItemsResponse not found in generated api.ts - please map or remove
export type BulkDeletePurchaseItemsResponse = any;
// TODO: BulkUpdatePurchaseItemsResponse not found in generated api.ts - please map or remove
export type BulkUpdatePurchaseItemsResponse = any;
export type CreateFamilyRequest = import('./api').CreateFamily;
// TODO: CreateNotificationRequest not found in generated api.ts - please map or remove
export type CreateNotificationRequest = any;
export type CreatePantryItemRequest = import('./api').CreatePantryItem;
export type CreateProductRequest = import('./api').CreateProduct;
// TODO: CreatePurchaseItemRequest not found in generated api.ts - please map or remove
export type CreatePurchaseItemRequest = any;
export type CreatePurchaseRequest = import('./api').CreatePurchase;
// TODO: CreateShoppingListItemRequest not found in generated api.ts - please map or remove
export type CreateShoppingListItemRequest = any;
export type CreateShoppingListRequest = import('./api').CreateShoppingList;
export type CreateStorePreferenceRequest = import('./api').CreateStorePreference;
export type CreateStoreRequest = import('./api').CreateStore;
// TODO: CreateUserRequest not found in generated api.ts - please map or remove
export type CreateUserRequest = any;
// TODO: CreditCardInvoice not found in generated api.ts - please map or remove
export type CreditCardInvoice = any;
// TODO: DeleteResponse not found in generated api.ts - please map or remove
export type DeleteResponse = any;
// TODO: EducationalContent not found in generated api.ts - please map or remove
export type EducationalContent = any;
// TODO: ExpenseFilters not found in generated api.ts - please map or remove
export type ExpenseFilters = any;
// TODO: ExpensesSummary not found in generated api.ts - please map or remove
export type ExpensesSummary = any;
export type ExtractDataFromPageRequest = import('./api').ExtractDataFromPageInput;
export type ExtractDataFromPdfRequest = import('./api').ExtractDataFromPdfInput;
export type ExtractFromReceiptPhotoRequest = import('./api').ExtractFromReceiptPhotoInput;
export type ExtractProductDataRequest = import('./api').ExtractProductDataInput;
// TODO: MarkAllNotificationsAsReadResponse not found in generated api.ts - please map or remove
export type MarkAllNotificationsAsReadResponse = any;
// TODO: MarkNotificationAsReadResponse not found in generated api.ts - please map or remove
export type MarkNotificationAsReadResponse = any;
// TODO: MeResponse not found in generated api.ts - please map or remove
export type MeResponse = any;
// TODO: Notification not found in generated api.ts - please map or remove
export type Notification = any;
// TODO: RefreshTokenResponse not found in generated api.ts - please map or remove
export type RefreshTokenResponse = any;
// TODO: RevokeTokenResponse not found in generated api.ts - please map or remove
export type RevokeTokenResponse = any;
// TODO: SignInRequest not found in generated api.ts - please map or remove
export type SignInRequest = any;
// TODO: SignUpRequest not found in generated api.ts - please map or remove
export type SignUpRequest = any;
export type SuggestMissingItemsRequest = import('./api').SuggestMissingItemsInput;
// TODO: UpdateFamilyRequest not found in generated api.ts - please map or remove
export type UpdateFamilyRequest = any;
// TODO: UpdatePantryItemRequest not found in generated api.ts - please map or remove
export type UpdatePantryItemRequest = any;
// TODO: UpdatePurchaseItemRequest not found in generated api.ts - please map or remove
export type UpdatePurchaseItemRequest = any;
// TODO: UpdatePurchaseRequest not found in generated api.ts - please map or remove
export type UpdatePurchaseRequest = any;
// TODO: UpdateShoppingListItemRequest not found in generated api.ts - please map or remove
export type UpdateShoppingListItemRequest = any;
// TODO: UpdateShoppingListRequest not found in generated api.ts - please map or remove
export type UpdateShoppingListRequest = any;
// TODO: UpdateStorePreferenceRequest not found in generated api.ts - please map or remove
export type UpdateStorePreferenceRequest = any;
// TODO: UpdateUserRequest not found in generated api.ts - please map or remove
export type UpdateUserRequest = any;
// TODO: UserStats not found in generated api.ts - please map or remove
export type UserStats = any;

// Provide a small compatibility surface: optional legacy fields and constants
// so existing web code can continue to compile while we migrate to canonical names.
export const MONTHLY_GROUPING_CONSTANTS = {
    MONTH_NAMES: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'] as const,
} as const;

// Module augmentation: add optional legacy property aliases that front-end code still uses.
declare global {
    // Make the MONTHLY_GROUPING_CONSTANTS visible as a global so generated
    // `api.ts` can reference it in type expressions.
    const MONTHLY_GROUPING_CONSTANTS: { MONTH_NAMES: readonly string[] };
}

declare module '@/types/api' {
    interface Product {
        // legacy convenience fields used by some UI code; keep optional and
        // non-conflicting with canonical `Product.unit: ProductUnit`.
        // Compatibility hints for imported/ocr products. Avoid redefining required BaseModel fields.
        price?: number;
        unitPrice?: number;
        quantity?: number;
        // older spelling variant
        subcategory?: string;
    }

    interface PurchaseItem {
        // UI expects these legacy names in some places
        purchaseDate?: string | Date;
        totalPrice?: number;
        productRef?: any;
        storeName?: string;
        id?: string;
        // some tests and code still supply `_id` on items
        _id?: string;
    }

    interface Purchase {
        // id alias used in some components
        id?: string;
        // alias for totalAmount vs total naming mismatch
        totalAmount?: number;
    }

    interface ShoppingList {
        id?: string;
    }
}

export {};
